### ISSUE TITLE
Retorno do código IBGE

### ISSUE THREAD

**Issue by DeivisFelipe** [lsnepomuceno/laravel-brazilian-ceps#5]
**Is your feature request related to a problem? Please describe.**
Não

**Describe the solution you'd like**
O CepEntity poderia ter o código IBGE, ele é muito Utíl para diversas coisas coisas, incluindo emissão de notas fiscais

**Describe alternatives you've considered**
O ViaCep já fornece o código IBGE, seria só adicionar ele a classe

**Additional context**
Não

**Versions involved:**

- Laravel: [e.g. 9.21]
- Laravel Brazilian Ceps [e.g. 0.0.18]
- Composer [e.g. 2.1]

**Comment by lsnepomuceno** [comment]
Vou incluir e adicionar aos testes.

**Comment by lsnepomuceno** [comment]
Versão https://github.com/lsnepomuceno/laravel-brazilian-ceps/releases/tag/0.0.5 liberada com inclusão do IBGE no CepEntity, lembrando que apenas os provedores OpenCep, Postomon e ViaCep possuem a informação, caso a informação não seja retornada no uso do pacote, o método getProviderName pode ser utilizado nas validações.
